version: '3.8'

volumes:
  mysql-volume:

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile #dockerfile：buildするDockerfileまでのパス
    ports:
      - 5173:5173    # vite用のポート番号
    volumes:
      - ./src/:/var/www/html
      - /src/node_modules   # 処理を早くするため
      - /src/vendor         # 処理を早くするため
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}      

  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - ${WEB_PORT}:80 #{ローカルのポート番号}:{Dockerコンテナのポート番号}
    depends_on: #depends_onはコンテナ間の依存関係を設定するオプション
      - app #appはPHP（アプリケーション）コンテナ NginxはPHPを実行するため、PHP→Nginxの順にコンテナを起動するように設定
    #depends_on:
    #– 先に起動するコンテナのサービス名
    volumes: #volumesはローカルとDockerコンテナ間のディレクトリ・ファイル等のリソースを対応つける設定するオプション
      - ./src/:/var/www/html #ローカルのリソースとDockerコンテナ内のリソースを:で対応
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    #volumes:
    #– (ローカルのリソース):(Dockerコンテナのリソース)
  db:
    image: mysql/mysql-server:latest
    container_name: db
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-volume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - ${PMA_PORT}:80
    # START phpmyadminに自動ログインする処理
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASSWORD}
    # END phpmyadminに自動ログインする処理
    volumes:
      - ./phpmyadmin/sessions:/sessions
    depends_on:
      - db
